version: '3'
services:
  microservice-transaction:
    container_name: microservice-transaction
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - ${MICROSERVICE_TRANSACTION_PORT}:9501
    links:
      - mysql
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      picpay_microservices_network:
        ipv4_address: ${MICROSERVICE_TRANSACTION_IP}
  kafka:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://kafka:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr kafka:33145
      - --advertise-rpc-addr kafka:33145
      - --smp 1
      - --memory 1G
      - --mode dev-container
      - --default-log-level=debug
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.3
    container_name: kafka
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    networks:
      picpay_microservices_network:
        ipv4_address: ${KAFKA_IP}
    ports:
      - "18081:18081"
      - "18082:18082"
      - "19092:19092"
      - "19644:9644"

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/vectorized/console:v2.2.4
    networks:
      - picpay_microservices_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://kafka:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka:9644"]
    ports:
      - "9002:8080"
    depends_on:
      - kafka
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      picpay_microservices_network:
        ipv4_address: ${MYSQL_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d

networks:
  picpay_microservices_network:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

volumes:
  redpanda-0: null
